SELECT TOP (1000) [ReservationID]
      ,[ReservationDate]
      ,[PartySize]
      ,[TableID]
      ,[RestaurantOpeningHours]
      ,[RestaurantPhoneNumber]
      ,[RestaurantAddress]
      ,[RestaurantID]
      ,[CustomerFirstName]
      ,[CustomerLastName]
  FROM [Restaurant Reservation Management ].[dbo].[Full_Reservation_Information]
